[package]
name = "bindiff"
version = "0.3.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.2.22"
crossterm = "0.25.0"
indicatif = "0.17.1"
